name: CI-CD Pipeline

# Déclenchement à chaque push ou pull request sur main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Étape 3 : installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : exécuter les tests
      - name: Run tests
        run: |
          pytest tests/   # à adapter selon ton projet

      # Étape 5 : construire l’image Docker
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Étape 6 : push sur Docker Hub (ou registry privée)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag myapp:latest mydockerhubusername/myapp:latest
          docker push mydockerhubusername/myapp:latest

      # Étape 7 : déploiement sur le serveur/cloud 
